# Generated by Django 3.2.4 on 2021-06-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='img',
            field=models.ImageField(default='store/images/products/product.png', upload_to='store/images/products'),
        ),
    ]
