# Generated by Django 3.2.4 on 2021-06-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210629_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart',
            field=models.BooleanField(default=False),
        ),
    ]
