# Generated by Django 3.2.4 on 2021-06-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cart_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart',
            new_name='ordered',
        ),
    ]
