# Generated by Django 3.2.4 on 2021-06-30 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_cart_cart_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
