# Generated by Django 3.2.4 on 2021-06-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210630_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='product',
        ),
        migrations.AddField(
            model_name='shipping',
            name='order',
            field=models.ManyToManyField(to='store.Cart'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Ordered'),
        ),
    ]
