# Generated by Django 3.2.4 on 2021-06-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_deliveryman_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
