# Generated by Django 3.2.8 on 2021-10-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_customer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='img',
            field=models.ImageField(upload_to='store/images/products'),
        ),
    ]
